version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8808:8808"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/sale
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - node

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sale
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  node:
    image: node:18
    container_name: node-app
    volumes:
      - ./node-app/Chinese_deliver:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3000:3000"

